/**
 * Generated by tsnapi — public API snapshot of `fumadocs-extras/page-actions/base-ui`
 */
// #region Variables
export declare const ViewOptionsPopover: (props: ViewOptionsPopoverProps) => import("react").ReactNode;
// #endregion

// #region Other
export { PageActionGroup }
export { PageActionId }
export { PageActionLabels }
export { PageActionLocale }
export { PageActionToggles }
export { ViewOptionsPopoverProps }
// #endregion